// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCarZw4PmWgxlfNHEABOEL7uXBwyYu-kSA',
    appId: '1:535869090620:web:c4a109552cfd05c9e5cc39',
    messagingSenderId: '535869090620',
    projectId: 'attendlite-97e52',
    authDomain: 'attendlite-97e52.firebaseapp.com',
    storageBucket: 'attendlite-97e52.firebasestorage.app',
    measurementId: 'G-K7L66N95QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx8fPZAdIiKGg88xaXGbgcSkMB-g7fglY',
    appId: '1:535869090620:android:a8cdcc6b120818b5e5cc39',
    messagingSenderId: '535869090620',
    projectId: 'attendlite-97e52',
    storageBucket: 'attendlite-97e52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQwOOjuljRLZmvYOrc2hO_eRmxF5bcURI',
    appId: '1:535869090620:ios:fdbb739459324dc9e5cc39',
    messagingSenderId: '535869090620',
    projectId: 'attendlite-97e52',
    storageBucket: 'attendlite-97e52.firebasestorage.app',
    iosBundleId: 'com.example.attendLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQwOOjuljRLZmvYOrc2hO_eRmxF5bcURI',
    appId: '1:535869090620:ios:fdbb739459324dc9e5cc39',
    messagingSenderId: '535869090620',
    projectId: 'attendlite-97e52',
    storageBucket: 'attendlite-97e52.firebasestorage.app',
    iosBundleId: 'com.example.attendLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCarZw4PmWgxlfNHEABOEL7uXBwyYu-kSA',
    appId: '1:535869090620:web:395dd8d7475f5ab1e5cc39',
    messagingSenderId: '535869090620',
    projectId: 'attendlite-97e52',
    authDomain: 'attendlite-97e52.firebaseapp.com',
    storageBucket: 'attendlite-97e52.firebasestorage.app',
    measurementId: 'G-MF927XJWG6',
  );
}
